[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "check-labels"
version = "0.1.0"
description = "Maintainer script for ngipkgs label syncing"
dependencies = [
    "requests",
    "rich",
    "beautifulsoup4",
]

[project.scripts]
check-labels = "check:main"

[tool.setuptools]
py-modules = ["check"]
